#:schema node_modules/wrangler/config-schema.json
name = "hxorz"
main = "src/index.js"
compatibility_date = "2025-12-15"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[placement]
mode = "smart"

routes = [
  "hxorz.cn/*",
  "*.hxorz.cn/*",
]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
